server:
  port: 8080
  servlet:
    context-path: /api/auth-server

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/userauth-service}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:0408}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
        format_sql: true
        default_schema: public
    open-in-view: false
    show-sql: true
    generate-ddl: true
  session:
    jdbc:
      initialize-schema: always
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: true
